version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cli
    binary: CLI
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}

archives:
  - id: cli-archive
    format: tar.gz
    name_template: >-
      CLI_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md

release:
  prerelease: auto
  name_template: "{{.Version}}"
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
